# Site settings
title: Develop Ookkaboard
email: ookkabat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning Meteor by Developing Ookkaboard (inspired by Discover Meteor)
baseurl: "/DevelopOokkaboard" # the subpath of your site, e.g. /blog/
url: "http://ookkabat.github.io" # the base hostname & protocol for your site
twitter_username: ookkabat
github_username:  ookkabat

timezone: Asia/Bangkok

exclude: [Gemfile, Gemfile.*, bs-config.js, params.json]

